//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazzini2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contatto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contatto()
        {
            this.Movimenti = new HashSet<Movimenti>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public System.DateTime DataDiNascita { get; set; }
        public string Indirizzo { get; set; }
        public string Citta { get; set; }
        public string EMail { get; set; }
        public string Telefono { get; set; }
        public enmTipoContatto TipoContatto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimenti> Movimenti { get; set; }
    }
}
