//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazzini2._0
{
    using System;
    
    public enum enmTipoContatto : int
    {
        Cliente = 0,
        Fornitore = 1
    }
}
