//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazzini2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimenti
    {
        public int ID { get; set; }
        public int IDProdotto { get; set; }
        public int IDMagazzino { get; set; }
        public int IDContatto { get; set; }
        public System.DateTime DataMovimento { get; set; }
        public string TipoMovimento { get; set; }
        public int Quantita { get; set; }
    
        public virtual Contatto Contatto { get; set; }
        public virtual Magazzini Magazzini { get; set; }
        public virtual Prodotti Prodotti { get; set; }
    }
}
